# Generated by Django 3.2.6 on 2021-08-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_alter_studentmanagement_roll_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmanagement',
            old_name='roll_no',
            new_name='rollno',
        ),
    ]
